### ISSUE TITLE
Past experiences

### ISSUE THREAD

**Issue by sabas** [M1dgard/OsmNewContributors#2]
Back in 2013 we had a tool to send the messages made by a polish user (balrog-kun), which I asked to setup for Italy, it used an OSM account (OSM Italia). I asked admins on IRC to unblock it after a while because was automatically banned for spam.
Here's a message from WelcomeWG in which there's a bit of recap https://lists.openstreetmap.org/pipermail/welcomewg/2013-February/000010.html

I'm interested and I'll add myself to the wiki :-)

**Comment by M1dgard** [comment]
We started welcoming users manually with the feed from resultmaps.neis-one.org. So far we've sent 167 messages and got 24 replies, none of which complained about the complexity, which is a bit better I think. :)
